#!/bin/bash

# brew系を実施
brew_targets=(zsh git hub peco zip tree lua vim colordiff nodebrew direnv autojump)
for target in ${brew_targets[@]}
do
  result=`brew list | grep ${target}`
  if [ -z ${result} ]; then
    brew install ${target}
  else
    echo "already installed ${target}"
  fi
done

## zsh
result=`grep '/usr/local/bin/zsh' /etc/shells`
if [ -z ${result} ]; then
  echo /usr/local/bin/zsh >> /etc/shells
  chsh -s /usr/local/bin/zsh
fi

## git
if [ ! -s $HOME/.gitconfig.local ]; then
  # 追記が必要
  cp -n .gitconfig.local.example $HOME/.gitconfig.local
  echo '追記が必要です。'
  echo $HOME/.gitconfig.local
fi

## nodebrew
if [ ! -e $HOME/.nodebrew/src ]; then
  mkdir -p $HOME/.nodebrew/src

  #nodebrew install v10.15.3
  nodebrew install-binary latest

  nodebrew list
  #nodebrew use v10.15.3
  nodebrew use stable
fi

## autojump
if [ ! -f $HOME/.curdir ]; then
  touch $HOME/.curdir
fi

# npm
## pure
result=`npm list --global | grep pure-prompt`
if [ -z "${result}" ]; then
  npm install --global pure-prompt
else
  echo 'already installed pure-prompt'
fi

# settings
## key-repeat
defaults write -g InitialKeyRepeat -int 10
defaults write -g KeyRepeat -float 1.3

result=`defaults read -g InitialKeyRepeat`
echo "InitialKeyRepeat ${result}"
result=`defaults read -g KeyRepeat`
echo "KeyRepeat ${result}"

# app
## iterm2
if [ ! -d $HOME/Applications/iTerm.app ]; then
  curl -L https://iterm2.com/downloads/stable/latest -o /tmp/iTerm2.zip
  unzip /tmp/iTerm2.zip
  mv -n /tmp/iTerm.app $HOME/Applications/iTerm.app
else
  echo 'already installed iTerm'
fi

# zshの拡張配置場所の用意
if [ ! -d $HOME/zsh ]; then
  mkdir $HOME/zsh
fi

## 絵文字
if [ ! -d $HOME/zsh/emoji-cli ]; then
  git clone https://github.com/b4b4r07/emoji-cli.git $HOME/zsh/emoji-cli
else
  echo 'already installed emoji-cli'
fi

## enhancd
if [ ! -d $HOME/zsh/enhancd ]; then
  git clone https://github.com/b4b4r07/enhancd.git $HOME/zsh/enhancd
else
  echo 'already installed enhancd'
fi
