#!/bin/bash

## zsh
brew install zsh
echo /usr/local/bin/zsh >> /etc/shells
chsh -s /usr/local/bin/zsh

## git
brew install git
brew install hub
# 追記が必要
cp -n .gitconfig.local.example ~/.gitconfig.local

## peco
brew install peco

## zip
brew install zip

## tree
brew install tree

## vim
brew install lua
brew reinstall vim

vim --version | grep lua

## colordiff
brew install colordiff

## node
brew install nodebrew
mkdir -p ~/.nodebrew/src
#nodebrew install v10.15.3
nodebrew install-binary latest

nodebrew list
#nodebrew use v10.15.3
nodebrew use stable

## pure
npm install --global pure-prompt

## key
defaults write -g InitialKeyRepeat -int 10
defaults write -g KeyRepeat -float 1.3

echo InitialKeyRepeat
defaults read -g InitialKeyRepeat
echo KeyRepeat
defaults read -g KeyRepeat

## iterm2
curl -L https://iterm2.com/downloads/stable/latest -o /tmp/iTerm2.zip
unzip /tmp/iTerm2.zip
mv -n /tmp/iTerm.app ~/Applications/iTerm.app

## direnv
brew install direnv
# .zshrc への追記
# eval "$(direnv hook zsh)"

# zshの拡張配置場所の用意
if [ ! -e $HOME/zsh ]; then
  mkdir $HOME/zsh
fi

# 絵文字
git clone https://github.com/b4b4r07/emoji-cli.git ~/zsh/emoji-cli

# enhancd
git clone https://github.com/b4b4r07/enhancd.git ~/zsh/enhancd
