#!/bin/bash

DOT_FILES=(.zshrc .vimrc .gitconfig .agignore)

for file in ${DOT_FILES[@]}
do
  if [ -f $HOME/$file ]; then
    mv $HOME/$file $HOME/dotfiles/bk/$file
  fi
  ln -s $HOME/dotfiles/$file $HOME/$file
done

## Gitディレクトリ系
GIT_DIRS=(git)

for dir in ${GIT_DIRS[@]}
do
  if [ -e $HOME/.$dir ]; then
    mv $HOME/.$dir $HOME/dotfiles/bk/.$dir
  fi
  ln -s $HOME/dotfiles/$dir $HOME/.$dir
done

## ディレクトリ系
DOT_DIRS=(.peco .vim/bundle/manual)

for dir in ${DOT_DIRS[@]}
do
  if [ -e $HOME/$dir ]; then
    if [ ! -e $HOME/dotfiles/bk/$dir ]; then
      mkdir -p $HOME/dotfiles/bk/$dir
    fi
    mv $HOME/$dir $HOME/dotfiles/bk/$dir
  fi
  ln -s $HOME/dotfiles/$dir $HOME/$dir
done

## コンフィグの中身
mkdir ~/.config
CONFIG_DOT_DIRS=(git karabiner)

for dir in ${CONFIG_DOT_DIRS[@]}
do
  if [ -e $HOME/.config/$dir ]; then
    mv $HOME/.config/$dir $HOME/dotfiles/bk/.config/$dir
  fi
  ln -s $HOME/dotfiles/.config/$dir $HOME/.config/$dir
done
